"""Bundled starter catalog parsed from ``Developer_Commands.docx``.

Regenerate after editing the Word file::

    uv run python scripts/generate_starter_data.py

Generated: 2026-05-23
"""

from __future__ import annotations

STARTER_DATA: list[dict] = [{'name': 'Django',
  'sections': [{'name': 'App Model Changes',
                'entries': [{'description': 'stages changes for implementation',
                             'command': 'python manage.py makemigrations'},
                            {'description': 'implements changes in db',
                             'command': 'python manage.py migrate'},
                            {'description': 'start the development server',
                             'command': 'python manage.py runserver'},
                            {'description': 'shell start Django shell — can access db directly '
                                            'from here',
                             'command': 'python manage.py'}]}]},
 {'name': 'Flask',
  'sections': [{'name': None,
                'entries': [{'description': 'start the dev server',
                             'command': 'flask --app <app name> run'},
                            {'description': 'debug mode', 'command': '<above command> --debug'},
                            {'description': 'open a shell', 'command': 'flask shell'}]}]},
 {'name': 'Git',
  'sections': [{'name': 'Branches',
                'entries': [{'description': 'delete a local branch',
                             'command': 'git branch -d <branch name>'},
                            {'description': 'list local branches', 'command': 'git branch'},
                            {'description': 'list remote branches', 'command': 'git branch -r'},
                            {'description': 'list ALL branches', 'command': 'git branch -r -a'},
                            {'description': 'create a new branch',
                             'command': 'git branch <branch name>'},
                            {'description': 'change branches',
                             'command': 'git checkout <branch name>'},
                            {'description': 'delete a remote branch',
                             'command': 'git push origin -d <branch name>'},
                            {'description': 'push local branch to origin remote',
                             'command': 'git push origin <branch name>'},
                            {'description': 'rename any branch',
                             'command': 'git branch -m <old name> <new name>'},
                            {'description': 'rename current branch',
                             'command': 'git branch -m <new name>'},
                            {'description': 'create or set remote branch',
                             'command': 'git push --set-upstream origin <branch name>'},
                            {'description': 'rename an upstream branch',
                             'command': 'git branch -m <old name> <new name> git push origin '
                                        '–delete <old name> git push --set-upstream origin <new '
                                        'name>'},
                            {'description': 'view an old commit',
                             'command': 'git checkout <commit hash>'},
                            {'description': 'compare commits of two branches',
                             'command': 'git show-branch <branch 1> <branch 2>'},
                            {'description': 'delete remote branch',
                             'command': 'git push -d origin <branch name>'}]},
               {'name': 'Reset Master/Main Branch to Another Branch',
                'entries': [{'description': '** All commits on the master branch are LOST in this '
                                            'process — use only if there is huge divergence **',
                             'command': 'git checkout master git reset --hard '
                                        '<path_to/remote/other_branch> git push -f'},
                            {'description': 'If you are trying to push too much data to the origin '
                                            '(for instance during an initial commit), and you get '
                                            'the error: fatal: the remote end hung up unexpectedly',
                             'command': 'git config http.postBuffer 524288000 git push -f'}]},
               {'name': 'Commits',
                'entries': [{'description': 'add additional to previous commit without changing '
                                            'the message',
                             'command': 'git commit --amend --no-edit'},
                            {'description': 'undo last commit and unstage changes',
                             'command': 'git reset HEAD~1'},
                            {'description': 'combine stage and commit commands',
                             'command': 'git commit -a -m “<message>”'},
                            {'description': 'add all to staging', 'command': 'git add .'}]},
               {'name': 'Config',
                'entries': [{'description': 'change username for repository',
                             'command': 'git config user.name <a name>'},
                            {'description': 'change username for all repositories',
                             'command': 'git config –global user.name <a name>'},
                            {'description': 'change email for repository',
                             'command': 'git config user.email <an email address>'},
                            {'description': 'change email for all repositories',
                             'command': 'git config user.email <an email address>'}]},
               {'name': 'Files',
                'entries': [{'description': 'diff of the same file in 2 branches (both branches '
                                            'committed)',
                             'command': 'git diff <branch 1> <branch 2> -- ./<file path to diff>'},
                            {'description': 'delete file that is already being indexed',
                             'command': 'git rm -r --cached <file name>'}]},
               {'name': 'Merges',
                'entries': [{'description': 'join changes from one branch to another',
                             'command': 'git merge <branch name>'},
                            {'description': 'pull changes from the parent',
                             'command': 'git pull --rebase'}]},
               {'name': 'Get Changes from Local Feature to Remote Development',
                'entries': [{'description': '1. commit changes on local feature branch',
                             'command': 'git commit -m “<message>”'},
                            {'description': '2. get latest changes from remote development branch '
                                            'to local development branch',
                             'command': 'git checkout development git pull --rebase'},
                            {'description': '3. Get the latest changes from local development '
                                            'branch into local feature-branch with your changes at '
                                            'the top',
                             'command': 'git checkout feature-branch git rebase development '
                                        '(optional) git log'},
                            {'description': '4. Get your changes over to from your feature branch '
                                            'to your local development branch (If you are doing '
                                            'cherry-pick, pick from bottom to top)',
                             'command': 'git checkout development git cherry-pick <commit id> git '
                                        'cherry-pick y'},
                            {'description': '5. Push the changes to development remote',
                             'command': 'git push origin development'},
                            {'description': '6. Check out Feature Branch',
                             'command': 'git checkout feature-branch'}]},
               {'name': 'Repositories',
                'entries': [{'description': 'create a new repository on the command line',
                             'command': 'git init git add README.md git commit -m "first commit" '
                                        'git remote add origin <path to remote repository> git '
                                        'push -u origin master'},
                            {'description': 'push an existing repository from the command line',
                             'command': 'git remote add origin <path to remote repository> git '
                                        'branch -M main git push -u origin master <path to local '
                                        'repository.git>'},
                            {'description': 'create a local copy of a remote',
                             'command': 'git clone <remote location> <clone name>'},
                            {'description': 'list project’s remotes', 'command': 'git remote -v'},
                            {'description': 'fetch work from the remote into the local',
                             'command': 'git fetch'},
                            {'description': 'same as above + prune deleted branches',
                             'command': 'git fetch -p'},
                            {'description': 'set up GitHub remote',
                             'command': 'https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github'}]}]},
 {'name': 'Launchd',
  'sections': [{'name': None,
                'entries': [{'description': 'launch a process',
                             'command': 'launchctl load ~/Library/LaunchAgents/<myscript.plist>'},
                            {'description': 'pause a process',
                             'command': 'launchctl unload ~/Library/LaunchAgents/<myscript.plist>'},
                            {'description': 'see if running',
                             'command': 'ps aux | grep <script.py>'},
                            {'description': 'list processes',
                             'command': 'launchctl list | grep <myscript>'},
                            {'description': 'stop gracefully', 'command': 'kill <PID>'},
                            {'description': 'stop immediately', 'command': 'kill -9 <PID>'},
                            {'description': 'plist permissions',
                             'command': 'chmod u=rwx,g=rwx,o=rx <my script>'},
                            {'description': 'permissions for .sh script executed by the .plist '
                                            'file',
                             'command': 'chmod 777 <my script>'},
                            {'description': 'manually run a process',
                             'command': 'launchctl start <my script>'}]}]},
 {'name': 'MongoDB',
  'sections': [{'name': None,
                'entries': [{'description': 'install MongoDB community version',
                             'command': 'https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/'},
                            {'description': 'sudo mongod --dbpath /users/admin/data/db/',
                             'command': 'sudo mongod --dbpath /users/admin/data/db/'},
                            {'description': 'mongosh', 'command': 'mongosh'},
                            {'description': 'show dbs', 'command': 'show dbs'}]}]},
 {'name': 'Nodeenv',
  'sections': [{'name': None,
                'entries': [{'description': 'activate Node venv',
                             'command': '. <general virtualenv dir>/<node env dir>/bin/activate'},
                            {'description': 'exit Node venv', 'command': 'deactivate_node'}]}]},
 {'name': 'Pip',
  'sections': [{'name': None,
                'entries': [{'description': 'install multiple packages listed in requirements.txt',
                             'command': 'pip install -r <requirements path>.txt'},
                            {'description': 'write all installed libraries to requirements.txt',
                             'command': 'pip freeze > requirements.txt'},
                            {'description': 'uninstall everything!',
                             'command': 'pip freeze | xargs pip uninstall -y'},
                            {'description': 'remove packages and their dependencies (must have '
                                            'pip-autoremove installed)',
                             'command': 'pip-autoremove <package name> -y'},
                            {'description': 'show package details',
                             'command': 'pip show <package name>'},
                            {'description': 'locate where pip.conf lives',
                             'command': 'pip config list --vv'},
                            {'description': 'install from GitHub repo',
                             'command': 'pip install git+https://github.com/<path to repository>'},
                            {'description': 'download but not install a package',
                             'command': 'pip download <package name>'},
                            {'description': 'install a version compatible with another version',
                             'command': 'pip install <package name> ~= <version number>'},
                            {'description': 'identify outdated packages',
                             'command': 'pip list --outdated'},
                            {'description': 'override python version requirements',
                             'command': '--ignore-requires-python'},
                            {'description': 'update a package',
                             'command': 'pip install -U <package_name>'},
                            {'description': 'scans all installed packages and reports any broken '
                                            'dependency constraints',
                             'command': 'pip check'}]}]},
 {'name': 'React (Vite)',
  'sections': [{'name': None,
                'entries': [{'description': 'start dev server', 'command': 'npm run dev'},
                            {'description': 'install dependency packages for a new project',
                             'command': 'npm install'}]}]},
 {'name': 'Unix',
  'sections': [{'name': None,
                'entries': [{'description': 'current date and time',
                             'command': '$(date +"%Y-%m-%d %H:%M:%S")'},
                            {'description': 'show contents of one file',
                             'command': 'cat <file_name>'},
                            {'description': 'change file name w/i directory',
                             'command': 'mv <old_file_name> <new_file_name>'},
                            {'description': 'jump to beginning of line', 'command': 'ctrl + A'},
                            {'description': 'clear everything from cursor onwards',
                             'command': 'ctrl + K'},
                            {'description': 'path to file or executable',
                             'command': 'which <file_name>'},
                            {'description': 'write a command’s output to a file (overwriting '
                                            'existing file)',
                             'command': '<command> > <path/to/file>'},
                            {'description': 'write a command’s output to a file (adding to '
                                            'existing file)',
                             'command': '<command> >> <path/to/file>'},
                            {'description': 'make a file executable',
                             'command': 'chmod +x <file name>'},
                            {'description': 'find out the size of a directory (all contents) (-s = '
                                            'recursively -h = human output)',
                             'command': 'du -sh <directory path>'},
                            {'description': 'erase last command', 'command': 'command + L'}]}]},
 {'name': 'Uvicorn',
  'sections': [{'name': None,
                'entries': [{'description': 'uvicorn main:app —reload',
                             'command': 'uvicorn main:app —reload'},
                            {'description': 'uvicorn main:app --host "0.0.0.0" --port 8000 '
                                            '--reload',
                             'command': 'uvicorn main:app --host "0.0.0.0" --port 8000 '
                                        '--reload'}]}]},
 {'name': 'Vi',
  'sections': [{'name': None,
                'entries': [{'description': 'Normal mode', 'command': 'Esc key'},
                            {'description': 'Command-line mode', 'command': ': key'},
                            {'description': 'quit', 'command': ':q'},
                            {'description': 'quit without saving', 'command': ':q!'},
                            {'description': 'write and quit', 'command': ':wq'},
                            {'description': 'force write and quit', 'command': ':wq!'},
                            {'description': 'exit', 'command': ':x'},
                            {'description': 'quit all', 'command': ':qa'},
                            {'description': 'quit without saving', 'command': ':cq'},
                            {'description': 'quit with save (Normal mode)', 'command': 'ZZ'},
                            {'description': 'quite without save (Normal mode)',
                             'command': 'ZQ'}]}]},
 {'name': 'Streamlit',
  'sections': [{'name': None,
                'entries': [{'description': 'launch program',
                             'command': 'streamlit run <script.py>'},
                            {'description': 'use built-in logger',
                             'command': '[above command] + --logger.level=<level>'}]}]},
 {'name': 'Apple',
  'sections': [{'name': None,
                'entries': [{'description': '** all of the below assume you have the correct '
                                            'package installed **',
                             'command': '** go to https://brew.sh/ to find to them on Homebrew **'},
                            {'description': 'update software purchased in AppStore',
                             'command': 'mas upgrade'},
                            {'description': 'display directory tree',
                             'command': 'tree <directory_name/>'},
                            {'description': 'temp directory location',
                             'command': '/private/var/folders/'}]}]},
 {'name': 'Python',
  'sections': [{'name': None,
                'entries': [{'description': 'create virtual environment',
                             'command': 'python<version> -m venv <path to venv>'},
                            {'description': 'update pip automatically upon venv creation',
                             'command': '--upgrade-deps'},
                            {'description': 'create a venv without pip',
                             'command': '--without-pip'},
                            {'description': 'have read-only access to global Python site-packages '
                                            'in the venv',
                             'command': '--system-site-packages'},
                            {'description': 'customize name in command prompt',
                             'command': '--prompt <desired name>'}]}]},
 {'name': 'ChatGPT (OpenAI)',
  'sections': [{'name': None,
                'entries': [{'description': 'logging in (as of 23-Nov-25) on a Chrome-based '
                                            'browser',
                             'command': 'Type in the address bar: chrome://flags/#enable-quic '
                                        'Disable Experimental QUIC protocol Restart chrome and try '
                                        'to login again'}]}]},
 {'name': 'Gunicorn',
  'sections': [{'name': None,
                'entries': [{'description': 'start the app with conf file',
                             'command': 'gunicorn -c gunicorn.conf.py app:app'},
                            {'description': 'start without conf file',
                             'command': 'gunicorn -k gevent -w 1 -b 127.0.0.1:5002 app:app'}]}]}]
